# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "gradle"
    ignore:
      - dependency-name: "org.spigotmc:spigot-api"
        versions:
          - "> 1.8.8-R0.1-SNAPSHOT"
      - dependency-name: "net.kyori:adventure-*"
        versions:
          - ">= 5.0.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"