main: "cc.dreamcode.template.TemplatePlugin"
version: "1.0-InDEV"
name: "Dream-Template"
description: "Dream-Template plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "author"
api-version: 1.13